// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpMYlCFpzT59qNhnT4A6ovyhx1UT5FgO4',
    appId: '1:346670400358:web:1b0e70f4f85caf117ebea7',
    messagingSenderId: '346670400358',
    projectId: 'divineshepherds-2003f',
    authDomain: 'divineshepherds-2003f.firebaseapp.com',
    storageBucket: 'divineshepherds-2003f.firebasestorage.app',
    measurementId: 'G-0PXB6E5EPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-k9f_8XFFfkcKRMSlGiXcQCRZtKoguAw',
    appId: '1:346670400358:android:0353f1e526a453ec7ebea7',
    messagingSenderId: '346670400358',
    projectId: 'divineshepherds-2003f',
    storageBucket: 'divineshepherds-2003f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7uw0phHP1pfKzjh-NqVADvHW8jeHv_Qo',
    appId: '1:346670400358:ios:ca0cd3aabd6a1fa47ebea7',
    messagingSenderId: '346670400358',
    projectId: 'divineshepherds-2003f',
    storageBucket: 'divineshepherds-2003f.firebasestorage.app',
    iosBundleId: 'com.example.shepherdsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7uw0phHP1pfKzjh-NqVADvHW8jeHv_Qo',
    appId: '1:346670400358:ios:ca0cd3aabd6a1fa47ebea7',
    messagingSenderId: '346670400358',
    projectId: 'divineshepherds-2003f',
    storageBucket: 'divineshepherds-2003f.firebasestorage.app',
    iosBundleId: 'com.example.shepherdsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpMYlCFpzT59qNhnT4A6ovyhx1UT5FgO4',
    appId: '1:346670400358:web:3eddd5fa3afaed817ebea7',
    messagingSenderId: '346670400358',
    projectId: 'divineshepherds-2003f',
    authDomain: 'divineshepherds-2003f.firebaseapp.com',
    storageBucket: 'divineshepherds-2003f.firebasestorage.app',
    measurementId: 'G-DHH6HDS3GX',
  );
}
